const sdk = [{
        'name': 'Solwave',
        slug: 'solwave',
        'tagline': 'Kotlin SDK to enable in-app transactions for Solana Mobile dApps.',
        'tags': ['KOTLIN'],
        'logo': 'https://pbs.twimg.com/profile_images/1702265630177857536/wCins9rY_400x400.jpg',
        'view': 'https://github.com/Saganize/Solwave-kt',
    },
    {
        'name': 'CandyPay',
        slug: 'candy-pay',
        'tagline': 'No-code builder powering Mobile Native NFT experiences on Solana',
        'tags': ['REACT NATIVE'],
        'logo': 'https://pbs.twimg.com/profile_images/1555879001365037058/TF_gD41F_400x400.jpg',
        'view': 'https://docs.candypay.fun/mobile-sdk/quickstart.html',
    },
    {
        'name': 'Metaplex-IOS',
        slug: 'metaplex-ios',
        'tagline': 'This SDK helps developers get started with the on-chain tools provided by Metaplex. ',
        'tags': ['SWIFT'],
        'logo': 'https://pbs.twimg.com/profile_images/1691961542387089408/DeGGPr6y_400x400.jpg',
        'view': 'https://github.com/metaplex-foundation/metaplex-ios',
    },
    {
        'name': 'Metaplex-Android',
        slug: 'metaplex-android',
        'tagline': 'This SDK helps developers get started with the on-chain tools provided by Metaplex.',
        'tags': ['ANDROID'],
        'logo': 'https://pbs.twimg.com/profile_images/1691961542387089408/DeGGPr6y_400x400.jpg',
        'view': 'https://github.com/metaplex-foundation/metaplex-android',
    },
    {
        'name': 'SolanaKT',
        slug: 'solana-kt',
        'tagline': 'This is a open source library on kotlin for Solana protocol.',
        'tags': ['KOTLIN'],
        'logo': 'https://pbs.twimg.com/profile_images/1691961542387089408/DeGGPr6y_400x400.jpg',
        'view': 'https://github.com/metaplex-foundation/SolanaKT',
    },
    {
        'name': 'Solana KMP',
        slug: 'solana-kmp',
        'tagline': 'This SDK leverages the power of Kotlin Multiplatform to enable developers to work with Solana blockchain across various platforms including Android, iOS Ecosystem, and the JVM.',
        'tags': ['KOTLIN MULTIPLATFORM'],
        'logo': 'https://pbs.twimg.com/profile_images/1691961542387089408/DeGGPr6y_400x400.jpg',
        'view': 'https://github.com/metaplex-foundation/solana-kmp',
    },
    {
        'name': 'Solana Swift',
        slug: 'solana-swift',
        'tagline': 'This is a open source library on pure swift for Solana protocol.',
        'tags': ['KOTLIN'],
        'logo': 'https://pbs.twimg.com/profile_images/1691961542387089408/DeGGPr6y_400x400.jpg',
        'view': 'https://github.com/metaplex-foundation/Solana.Swift',
    },
    {
        'name': 'Espresso Cash Public',
        slug: 'espresso-cash-public',
        'tagline': 'Dart and Flutter apps and libraries maintained by Espresso Cash team for Solana.',
        'tags': ['DART'],
        'logo': 'https://pbs.twimg.com/profile_images/1631702586108657665/o4WYbbHh_400x400.jpg',
        'view': 'https://github.com/espresso-cash/espresso-cash-public',
    },
];


export default sdk;